### PR TITLE
Create github action to deploy preview of changes from PR to firebase.

### PR DESCRIPTION
**Pull request by ThatRanga**

### CODE REVIEW

**Comment by rissole** [comment]
do we need this? could encroach on firebase free tier, and taking a video isnt very difficult.

**Comment by ThatRanga** [comment]
We've done only 2mb in the last 7 days https://console.firebase.google.com/project/wow-board-game/hosting/usage/last-7d/storage and the free tier is 360 mb/day with 10GB overall. I don't think we'll come close to hitting that limit anytime soon https://firebase.google.com/pricing

**Review by rissole — APPROVED** [review]

**Comment by rissole** [comment]
i mean we are just gonna keep adding assets and we can just merge PRs, really feel like it's overkill but lets try it out!

**Comment by ThatRanga** [comment]
Yeah, if people aren't using it we can take it out.

**Pull request merged**
