### PR TITLE
Refactor main app out to separate screens

### PR DESCRIPTION
**Pull request by bqx**
Also add a font and implement simple screen toggle

### CODE REVIEW

**Review by blakedovetail — CHANGES_REQUESTED** [review]
this handles different "lists" like toggling between inventory and powers, but doesnt work well for loading and character selection. 

with this architecture the loading screen and character selection would sit within the nav and character stats chrome.

would prefer different screens to replace the whole app, hiding stats and nav, and inventory vs. powers to be called "lists" or something instead of screens

**Comment by bqx** [comment]
yeah we could split out "screens" (loading/character-select/main) and then have different "lists" in the main app which re-use the top/bottom nav

**Review by blakedovetail — APPROVED** [review]

**Comment by blakedovetail** [comment]
nice one benny

**Comment by blakedovetail** [comment]
oops IM ON MY WORK ACCOUNT

**Review by blakedovetail — APPROVED** [review]

**Review by rissole — APPROVED** [review]

**Pull request merged**
